### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kumapachi** [kumapachi/protospace-38528#1]
#URL
https://protospace-38528.onrender.com/

**Comment by shodai-ito** [comment]
@kumapachi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`コメント機能`**
- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
自身のプロトタイプに空のフォームでコメントしようとすると、エラー画面に遷移してしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by kumapachi** [comment]
レビューありがとうございました。指摘箇所修正しました。

**Comment by motomuun** [comment]
@kumapachi さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
